server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #uri以lb://开头,后面接的就是你需要转发到的服务名称 Netflix Ribbon
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由


        - id: payment_routh2
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
#          filters:
#            - AddResponseHeader=X-Request-Id, \d
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
#            - After=2020-07-25T04:19:35.561+08:00[Asia/Shanghai]
#            - Cookie=username,lzy
#            - Header=X-Request-Id, \d+



eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


